// src/user/components/Form.jsx
import React, { Component } from 'react'

export default class extends Component {

    render(){
        return (
            <form className='ui form' action={this.props.action} method='post'>
                <div className='field'>
                    <label>name</label>
                    <input type='text' name='user[name]' value={this.props.name} />
                </div>

                <div className='field'>
                    <label>furigana</label>
                    <input type='text' name='user[furigana]' value={this.props.furigana} />
                </div>

                <div className='field'>
                    <label>mail address</label>
                    <input type='text' name='user[mailAddress]' value={this.props.mailAddress} />
                </div>

                <button className='ui button' type='submit'>regist</button>
            </form>
        )
    }

}

// src/users/Form.vue
<template>
  <form method='post'>
    <div>
      <label>name</label>
      <input type='text'>
    </div>

    <div>
      <label>furigana</label>
      <input type='text'>
    </div>

    <div>
      <label>mail address</label>
      <input type='text'>
    </div>

    <button type='submit'>regist</button>
  </form>
</template>

<script>
export default {
}
</script>

<style scoped>

</style>
