// views/users/index.jsx
var React = require('react');
var DefaultLayout = require('../DefaultLayout');
var Table = require('../components/Table');

module.exports = React.createClass({
    render: function(){
        return (
            <DefaultLayout>
                <h1>users list</h1>
                <form className='ui search'>
                    <div className='ui icon input'>
                        <input className='prompt' type='text' name='q' placeholder='search' value={this.props.query.q} />
                        <i className='search icon'></i>
                    </div>
                </form>
                <UserList users={this.props.users}>
                </UserList>
                <a href='/users/new'>new user</a>
            </DefaultLayout>
        );
    }
});


var UserList = React.createClass({
    render: function(){
        var tbody = this.props.users.map(function(user){
            return (
                <tr>
                    <td>{user.name}</td>
                    <td>{user.furigana}</td>
                    <td>{user.mailAddress}</td>
                    <td>
                        <a href={'/users/' + user._id}>show</a>
                    </td>
                    <td>
                        <a href={'/users/' + user._id + '/edit'}>edit</a>
                    </td>
                </tr>
            );
        });

        return (
            <Table>
                <thead>
                    <tr>
                        <th>name</th>
                        <th>furigana</th>
                        <th>mail address</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {tbody}
                </tbody>
                <tfoot>
                    <tr>
                        <th colSpan='5'>
                            Total: {this.props.users.length}
                        </th>
                     </tr>
                </tfoot>
            </Table>
        );
    }
})

// src/users/Index.vue
<template>

  <h1>user list</h1>

  <form v-on:submit.prevent='search'>
    <input type='search' name='q' v-model='q' placeholder='search'>
  </form>

  <table>
    <thead>
      <tr>
        <th>name</th>
        <th>furigana</th>
        <th>mail address</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr v-for='user in users'>
        <td>{{user.name}}</td>
        <td>{{user.furigana}}</td>
        <td>{{user.mailAddress}}</td>
        <td>
          <a v-link='{path: "users/" + user._id + "/edit"}'>edit</a>
          <button v-on:click='del(user)'>delete</button>
        </td>
      </tr>
    </tbody>
  </table>

  <a v-link="{path:'users/new'}">new user</a>

</template>

<script>
import request from '../request/user'

export default {
  data() {
    return {
      users: [],
      q: this.$route.query.q
    }
  },
  route: {
    data({ to, next }){
      let { query } = to

      request
        .query(query)
        .end(function(err, res){
          let users = res.body
          next({users})
        })

    },
  },
  methods: {
    search(e){
      this.$router.go('?q=' + this.q)
    },
    del(user){
      request.delete(user._id).end((err, res) => {
        this.users = this.users.filter((u) => u._id !== user._id)
      })
    }
  },
}
</script>

<style scoped>

</style>
